(() => {
  'use strict';

  /* Electrical Layout Script editor. The model is plain JSON; SVG is derived from it. */
  const NS = 'http://www.w3.org/2000/svg';
  const W = 800, H = 1130, SNAP = 20, STORAGE = 'electrical-layout-maker-v2';
  const LABELS = { led:'LED', fan:'Fan', socket15:'15 A Socket', socket5:'5 A Socket' };
  const SYMBOL_SIZE = { led:[20,20], fan:[60,60], socket15:[70,44], socket5:[50,36] };
  const DEFAULTS = {
    room:{x:40,y:80,w:700,h:1050}, divider:{x:40,y:580,w:700,h:1,orientation:'h'}, box:{x:260,y:760,w:200,h:80,label:'Box\nType here',labelPos:'inside',size:14}, text:{x:250,y:42,w:240,h:28,label:'Ground Floor Plan',size:20,align:'center'}, legend:{x:585,y:100,w:195,h:210,auto:true}
  };
  const $ = id => document.getElementById(id);
  const qsa = sel => [...document.querySelectorAll(sel)];
  const state = { doc:{version:1,symbolSet:'house-v1',page:{size:'A4',orientation:'portrait',border:true,w:W,h:H},objects:[]}, selectedId:null, selectedIds:[], tool:'select', history:[], future:[], nextId:1, grid:true, snap:true, zoom:1, drag:null, resize:null, rotate:null, marquee:null, preview:null, lastImport:null };

  const clone = value => JSON.parse(JSON.stringify(value));
  const uid = () => `o${state.nextId++}`;
  const objectById = id => state.doc.objects.find(o => o.id === id);
  const selected = () => objectById(state.selectedId);
  const selectedObjects = () => state.selectedIds.map(objectById).filter(Boolean);
  const clamp = (n,a,b) => Math.max(a,Math.min(b,n));
  const num = v => Number.parseFloat(String(v).replace('%',''));
  const snap = n => state.snap ? Math.round(n / SNAP) * SNAP : n;
  function snapshot(){ return JSON.stringify({doc:state.doc,nextId:state.nextId}); }
  function restore(raw){ const s=JSON.parse(raw); state.doc=s.doc; state.nextId=s.nextId||1; state.selectedId=null; state.selectedIds=[]; render(); }
  function record(){ state.history.push(snapshot()); if(state.history.length>80)state.history.shift(); state.future=[]; }
  function undo(){ if(!state.history.length)return toast('Nothing to undo'); state.future.push(snapshot()); restore(state.history.pop()); toast('Undone'); }
  function redo(){ if(!state.future.length)return toast('Nothing to redo'); state.history.push(snapshot()); restore(state.future.pop()); toast('Redone'); }

  function roomFor(obj){if(obj?.room){const exact=state.doc.objects.find(o=>o.type==='room'&&o.id===obj.room);if(exact)return exact;}const x=(obj?.x||0)+(obj?.w||0)/2,y=(obj?.y||0)+(obj?.h||0)/2;return state.doc.objects.find(o=>o.type==='room'&&x>=o.x&&x<=o.x+o.w&&y>=o.y&&y<=o.y+o.h)||state.doc.objects.find(o=>o.type==='room');}
  function parsePosition(token, axis, room){ const s=String(token).trim(); if(s.endsWith('%') && room) return room[axis==='x'?'x':'y'] + (num(s)/100) * room[axis==='x'?'w':'h']; return num(s); }
  function symbolDims(symbol){ const [w,h]=SYMBOL_SIZE[symbol]||[40,40]; return {w,h}; }
  function createObject(type, props={}){ const o={id:uid(),type,x:0,y:0,w:40,h:40,rotation:0,label:'',...props}; if(type==='symbol'){const d=symbolDims(o.symbol);o.w=o.w||d.w;o.h=o.h||d.h;} state.doc.objects.push(o); return o; }

  function svgEl(tag,attrs,parent){ const e=document.createElementNS(NS,tag); Object.entries(attrs||{}).forEach(([k,v])=>e.setAttribute(k,v)); if(parent)parent.appendChild(e); return e; }
  function svgText(parent,value,attrs){ const t=svgEl('text',attrs,parent); t.textContent=value; return t; }
  function drawReferenceSymbol(g,symbol,w,h){
    const st={fill:'none',stroke:'#111','stroke-width':2,'stroke-linecap':'round','stroke-linejoin':'round'};
    if(symbol==='led'){svgEl('circle',{cx:w/2,cy:h/2,r:Math.min(w,h)*.4,...st},g);return;}
    if(symbol==='fan'){const cx=w/2,cy=h/2,r=Math.min(w,h)/2-2,f=r*.58,k=r*.34;svgEl('circle',{cx,cy,r,...st},g);svgEl('path',{d:`M${cx} ${cy}C${cx+k} ${cy-k*.8} ${cx+k} ${cy-f} ${cx} ${cy-f}C${cx-k} ${cy-f} ${cx-k} ${cy-k*.8} ${cx} ${cy}C${cx+k} ${cy+k*.8} ${cx+k} ${cy+f} ${cx} ${cy+f}C${cx-k} ${cy+f} ${cx-k} ${cy+k*.8} ${cx} ${cy}`,...st},g);return;}
    /* sockets: closed half-circle(s) + 3 rays on the outer one. 15A = two nested half-circles, 5A = one. */
    const s=Math.min(w/70,h/44),sg=svgEl('g',{transform:`translate(${(w-70*s)/2} ${(h-44*s)/2}) scale(${s})`},g);
    const d=symbol==='socket15'?'M11 40A24 24 0 0 1 59 40Z M21 40A14 14 0 0 1 49 40Z M35 13V3M50.5 17.9L56.2 9.7M19.5 17.9L13.8 9.7':'M15 40A20 20 0 0 1 55 40Z M35 17V7M49.8 22.4L56.2 14.7M20.2 22.4L13.8 14.7';
    svgEl('path',{d,...st,'stroke-width':2/s},sg);
  }
  function wallGeometry(o){ const r=roomFor(o)||{x:40,y:80,w:700,h:1050}; const along=clamp(Number(o.along??50),0,100)/100; const {w,h}=symbolDims(o.symbol); let bx,by,rot; if(o.wall==='right'){bx=r.x+r.w;by=r.y+r.h*along;rot=-90;}else if(o.wall==='top'){bx=r.x+r.w*along;by=r.y;rot=180;}else if(o.wall==='left'){bx=r.x;by=r.y+r.h*along;rot=90;}else{bx=r.x+r.w*along;by=r.y+r.h;rot=0;} return {bx,by,rot,w,h,localX:35,localY:40}; }
  /* Wall placement is only a helper: it converts to a normal free symbol (x,y,rotation) so it can always be moved/rotated. */
  function wallToFree(o,r){r=r||{x:40,y:80,w:700,h:1050};const a=clamp(Number(o.along??50),0,100)/100,s0=symbolDims(o.symbol),w=o.w||s0.w,h=o.h||s0.h;let bx,by,rot;if(o.wall==='right'){bx=r.x+r.w;by=r.y+r.h*a;rot=-90}else if(o.wall==='top'){bx=r.x+r.w*a;by=r.y;rot=180}else if(o.wall==='left'){bx=r.x;by=r.y+r.h*a;rot=90}else{bx=r.x+r.w*a;by=r.y+r.h;rot=0}const t=rot*Math.PI/180,k=h*.41;o.w=w;o.h=h;o.rotation=rot;o.x=bx+Math.sin(t)*k-w/2;o.y=by-Math.cos(t)*k-h/2;delete o.wall;delete o.along;delete o.room;return o;}
  function snapToWall(o){if(!state.snap||o.type!=='symbol'||!o.symbol.startsWith('socket'))return;const r=state.doc.objects.find(x=>x.type==='room');if(!r)return;const cx=o.x+o.w/2,cy=o.y+o.h/2,c=[['left',Math.abs(cx-r.x)],['right',Math.abs(cx-r.x-r.w)],['top',Math.abs(cy-r.y)],['bottom',Math.abs(cy-r.y-r.h)]].sort((a,b)=>a[1]-b[1])[0];if(c[1]>40)return;const v=c[0]==='left'||c[0]==='right';wallToFree(Object.assign(o,{wall:c[0],along:((v?cy-r.y:cx-r.x)/(v?r.h:r.w))*100}),r);}
  function renderSymbolObject(g,o){const rot=o.rotation||0;g.setAttribute('transform',`translate(${o.x} ${o.y}) rotate(${rot} ${o.w/2} ${o.h/2})`);svgEl('rect',{x:-4,y:-4,width:o.w+8,height:o.h+8,fill:'transparent',class:'obj-hit'},g);drawReferenceSymbol(g,o.symbol,o.w,o.h);if(o.label)svgText(g,o.label,{x:o.w/2,y:o.h+15,class:'object-label',transform:`rotate(${-rot} ${o.w/2} ${o.h+15})`});}
  function addObjectHitTarget(g,o){let x=o.x||0,y=o.y||0,w=o.w||40,h=o.h||40;if(o.type==='divider'&&o.orientation==='v'){x-=12;w=24;}else if(o.type==='divider'){y-=12;h=24;}else if(o.type==='text'){x-=24;w=Math.max(w||40,48);h=Math.max(h||30,38);}svgEl('rect',{x:x-8,y:y-8,width:w+16,height:h+16,fill:'transparent',stroke:'none',class:'obj-hit'},g);}
  function addRoomEdgeTargets(g,o){const t=20,x=o.x,y=o.y,w=o.w,h=o.h;[[x-t/2,y-t/2,w+t,t],[x-t/2,y+h-t/2,w+t,t],[x-t/2,y+t/2,t,Math.max(0,h-t)],[x+w-t/2,y+t/2,t,Math.max(0,h-t)]].forEach(([rx,ry,rw,rh])=>svgEl('rect',{x:rx,y:ry,width:rw,height:rh,fill:'transparent',stroke:'none',class:'obj-hit'},g));}
  function renderObject(o,parent,preview=false){ const g=svgEl('g',{class:preview?'preview-object':'obj','data-id':o.id},parent); if(o.type==='symbol'){renderSymbolObject(g,o);return g;}if(o.type==='room')addRoomEdgeTargets(g,o);else addObjectHitTarget(g,o);if(o.rotation)g.setAttribute('transform',`rotate(${o.rotation} ${o.x+o.w/2} ${o.y+o.h/2})`); if(o.type==='room'){svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,class:'room-stroke','pointer-events':'none'},g);if(o.name)svgText(g,o.name,{x:o.x+10,y:o.y+20,fill:'#111','font-size':12,'font-family':'Arial','font-weight':'700','pointer-events':'none'});return g;} if(o.type==='divider'){if(o.orientation==='v')svgEl('line',{x1:o.x,y1:o.y,x2:o.x,y2:o.y+o.h,class:'divider-stroke','pointer-events':'none'},g);else svgEl('line',{x1:o.x,y1:o.y,x2:o.x+o.w,y2:o.y,class:'divider-stroke','pointer-events':'none'},g);return g;} if(o.type==='box'){svgEl('rect',{x:o.x,y:o.y,width:o.w,height:o.h,class:'symbol-stroke',style:'fill:transparent;pointer-events:none'},g);const ls=String(o.label||'').split('\n'),fs=o.size||14,lh=fs*1.25,y0=o.labelPos==='below'?o.y+o.h+fs+4:o.y+o.h/2-(ls.length-1)*lh/2+fs*.35;ls.forEach((ln,i)=>svgText(g,ln,{x:o.x+o.w/2,y:y0+i*lh,class:'object-label',style:`font-size:${fs}px`,'pointer-events':'none'}));return g;} if(o.type==='text'){const align=o.align||'start',tx=align==='center'?o.x+o.w/2:align==='end'?o.x+o.w:o.x;String(o.label||o.text||'').split('\n').forEach((ln,i)=>svgText(g,ln,{x:tx,y:o.y+(o.size||20)*(1+i*1.25),fill:'#111','font-family':'Arial','font-size':o.size||20,'text-anchor':align,...(ln?{textLength:Math.max(1,o.w),lengthAdjust:'spacingAndGlyphs'}:{}),'pointer-events':'none'}));return g;} if(o.type==='legend'){renderLegend(g,o);return g;}return g; }
  function renderLegend(g,o){ const types=[...new Set(state.doc.objects.filter(x=>x.type==='symbol').map(x=>x.symbol))];const row=38;const height=Math.max(o.h,34+types.length*row);svgEl('rect',{x:o.x,y:o.y,width:o.w,height,fill:'#fff',stroke:'#111','stroke-width':2},g);svgText(g,'REFERENCE SYMBOLS',{x:o.x+o.w/2,y:o.y+17,'text-anchor':'middle','font-family':'Arial','font-size':11,'font-weight':800,fill:'#111'});svgEl('line',{x1:o.x+5,y1:o.y+26,x2:o.x+o.w-5,y2:o.y+26,stroke:'#111','stroke-width':1},g);types.forEach((type,i)=>{const mini=svgEl('g',{transform:`translate(${o.x+10} ${o.y+34+i*row}) scale(.55)`},g);drawReferenceSymbol(mini,type,...SYMBOL_SIZE[type]);svgText(g,LABELS[type],{x:o.x+53,y:o.y+48+i*row,fill:'#111','font-family':'Arial','font-size':11,'font-weight':600});});}
  function selectionRect(o){ if(o.wall){const z=wallGeometry(o);return{x:z.bx-z.w/2,y:z.by-z.h/2,w:z.w,h:z.h,rot:z.rot};}return{x:o.x,y:o.y,w:o.w,h:o.h,rot:o.rotation||0}; }
  function renderSelection(){const layer=$('selectionLayer');layer.innerHTML='';if(state.marquee){const m=state.marquee;svgEl('rect',{x:Math.min(m.x,m.cx),y:Math.min(m.y,m.cy),width:Math.abs(m.cx-m.x),height:Math.abs(m.cy-m.y),class:'selection-box'},layer);}const os=selectedObjects();if(!os.length)return;let r;if(os.length===1)r=selectionRect(os[0]);else{const bounds=os.map(selectionRect);const x=Math.min(...bounds.map(b=>b.x)),y=Math.min(...bounds.map(b=>b.y)),right=Math.max(...bounds.map(b=>b.x+b.w)),bottom=Math.max(...bounds.map(b=>b.y+b.h));r={x,y,w:right-x,h:bottom-y,rot:0};}const pad=Math.max(7,20-Math.min(r.w,r.h)*.1),g=svgEl('g',{transform:`rotate(${r.rot||0} ${r.x+r.w/2} ${r.y+r.h/2})`},layer);svgEl('rect',{x:r.x-pad,y:r.y-pad,width:r.w+pad*2,height:r.h+pad*2,class:'selection-box','pointer-events':'none'},g);if(os.length>1)return;const points=[['nw',r.x-pad,r.y-pad],['n',r.x+r.w/2,r.y-pad],['ne',r.x+r.w+pad,r.y-pad],['e',r.x+r.w+pad,r.y+r.h/2],['se',r.x+r.w+pad,r.y+r.h+pad],['s',r.x+r.w/2,r.y+r.h+pad],['sw',r.x-pad,r.y+r.h+pad],['w',r.x-pad,r.y+r.h/2]];points.forEach(([corner,x,y])=>{const hit=svgEl('rect',{x:x-24,y:y-24,width:48,height:48,rx:4,class:`selection-hit handle-${corner}`,'data-resize':corner},g);hit.addEventListener('pointerdown',e=>startResize(e,corner));svgEl('rect',{x:x-6,y:y-6,width:12,height:12,rx:2,class:'selection-handle','pointer-events':'none'},g);});const cx=r.x+r.w/2,top=r.y-pad;svgEl('line',{x1:cx,y1:top,x2:cx,y2:top-32,stroke:'#2b70e8','stroke-width':2,'pointer-events':'none'},g);const rh=svgEl('circle',{cx,cy:top-32,r:24,class:'rotation-hit'},g);rh.addEventListener('pointerdown',startRotate);svgEl('circle',{cx,cy:top-32,r:7,class:'rotation-handle','pointer-events':'none'},g);}
  function render(){const page=state.doc.page||{w:W,h:H};$('drawing').setAttribute('viewBox',`0 0 ${page.w||W} ${page.h||H}`);$('drawing').querySelector('.paper').setAttribute('width',page.w||W);$('drawing').querySelector('.paper').setAttribute('height',page.h||H);$('grid').setAttribute('width',page.w||W);$('grid').setAttribute('height',page.h||H);const layer=$('objects');layer.innerHTML='';state.doc.objects.forEach(o=>{const g=renderObject(o,layer);if(!state.preview){g.addEventListener('pointerdown',onObjectDown);g.addEventListener('dblclick',()=>{$('properties').classList.add('open');$('propLabel').focus();});}});renderSelection();updateProperties();$('objectCount').textContent=`${state.doc.objects.length} objects`;$('emptyState').classList.toggle('show',state.doc.objects.length===0);$('grid').classList.toggle('hidden',!state.grid);}

  function point(e){const p=$('drawing').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const c=$('drawing').getScreenCTM();const q=p.matrixTransform(c.inverse());return{x:q.x,y:q.y};}
  function hitObjectAt(o,p){if(o.type==='room')return Math.min(Math.abs(p.x-o.x),Math.abs(p.x-o.x-o.w),Math.abs(p.y-o.y),Math.abs(p.y-o.y-o.h))<14;if(o.type==='divider')return o.orientation==='v'?Math.abs(p.x-o.x)<14&&p.y>=o.y&&p.y<=o.y+o.h:Math.abs(p.y-o.y)<14&&p.x>=o.x&&p.x<=o.x+o.w;const c={x:o.x+o.w/2,y:o.y+o.h/2},v=rotateVector(p.x-c.x,p.y-c.y,-(o.rotation||0));return Math.abs(v.x)<=o.w/2+8&&Math.abs(v.y)<=o.h/2+8;}
  function onObjectDown(e){if(state.tool!=='select')return;e.stopPropagation();let id=e.currentTarget.dataset.id;if(!id)return;const p=point(e);if(e.altKey){const hits=state.doc.objects.filter(o=>hitObjectAt(o,p));const at=hits.findIndex(o=>o.id===id);if(hits.length)id=hits[(at+1+hits.length)%hits.length].id;}const additive=e.shiftKey||e.ctrlKey||e.metaKey;if(additive){state.selectedIds=state.selectedIds.includes(id)?state.selectedIds.filter(x=>x!==id):[...state.selectedIds,id];state.selectedId=state.selectedIds.at(-1)||null;renderSelection();updateProperties();$('properties').classList.add('open');$('drawing').setPointerCapture?.(e.pointerId);return;}if(!state.selectedIds.includes(id))state.selectedIds=[id];state.selectedId=id;$('properties').classList.add('open');renderSelection();updateProperties();const ids=state.selectedIds.slice(),starts=ids.map(key=>{const o=objectById(key);return{id:key,x:o.x,y:o.y,along:o.along,wall:o.wall};});state.drag={ids,startX:p.x,startY:p.y,before:snapshot(),moved:false,starts};$('drawing').setPointerCapture?.(e.pointerId);}
  function onCanvasDown(e){const p=point(e);if(state.tool!=='select'){record();const o=makeFromTool(state.tool,p);snapToWall(o);state.doc.objects.push(o);state.selectedId=o.id;state.selectedIds=[o.id];state.tool='select';setTool('select');render();toast(`${objectLabel(o)} added`);return;}if(e.target!==$('drawing')&&!e.target.classList.contains('paper')&&!e.target.classList.contains('grid'))return;if(e.shiftKey){state.marquee={x:p.x,y:p.y,cx:p.x,cy:p.y,additive:true,before:state.selectedIds.slice()};$('drawing').setPointerCapture?.(e.pointerId);renderSelection();return;}deselect();}
  function rotateVector(x,y,degrees){const r=degrees*Math.PI/180;return{x:x*Math.cos(r)-y*Math.sin(r),y:x*Math.sin(r)+y*Math.cos(r)};}
  /* All gestures retain SVG-level pointer capture while SVG children refresh. */
  function onMove(e){const p=point(e);if(state.marquee){state.marquee.cx=p.x;state.marquee.cy=p.y;renderSelection();return;}if(state.drag){let dx=p.x-state.drag.startX,dy=p.y-state.drag.startY;state.drag.moved ||= Math.abs(dx)+Math.abs(dy)>2;const ss=state.drag.starts.filter(s=>!s.wall),minX=Math.min(...ss.map(s=>s.x),0),minY=Math.min(...ss.map(s=>s.y),0),maxX=Math.max(...ss.map(s=>s.x+(objectById(s.id)?.w||0)),0),maxY=Math.max(...ss.map(s=>s.y+(objectById(s.id)?.h||0)),0);dx=clamp(dx,-minX,W-maxX);dy=clamp(dy,-minY,H-maxY);if(state.snap){dx=snap(dx);dy=snap(dy);}for(const s of state.drag.starts){const o=objectById(s.id);if(!o)continue;if(s.wall){const room=roomFor(o);if(room)o.along=clamp((s.wall==='top'||s.wall==='bottom'?(s.along/100*room.w+dx)/room.w:(s.along/100*room.h+dy)/room.h)*100,0,100);}else{o.x=s.x+dx;o.y=s.y+dy;}}render();return;}if(state.resize){const o=objectById(state.resize.id);if(!o)return;const s=state.resize,rot=o.rotation||0,v=rotateVector(p.x-s.startX,p.y-s.startY,-rot),c=s.corner;let nw=s.ow,nh=s.oh;if(c.includes('e'))nw=s.ow+v.x;if(c.includes('w'))nw=s.ow-v.x;if(c.includes('s'))nh=s.oh+v.y;if(c.includes('n'))nh=s.oh-v.y;nw=Math.max(8,nw);nh=Math.max(8,nh);const ax=c.includes('w')?s.ow:0,ay=c.includes('n')?s.oh:0,fx=c.includes('w')?nw:0,fy=c.includes('n')?nh:0,oldCenter={x:s.ox+s.ow/2,y:s.oy+s.oh/2},anchorOffset=rotateVector(ax-s.ow/2,ay-s.oh/2,rot),anchor={x:oldCenter.x+anchorOffset.x,y:oldCenter.y+anchorOffset.y},newOffset=rotateVector(fx-nw/2,fy-nh/2,rot),newCenter={x:anchor.x-newOffset.x,y:anchor.y-newOffset.y};o.x=clamp(newCenter.x-nw/2,0,W-nw);o.y=clamp(newCenter.y-nh/2,0,H-nh);o.w=nw;o.h=nh;if(o.type==='text')o.size=clamp(s.size*nh/s.oh,8,100);render();return;}if(state.rotate){const o=objectById(state.rotate.id);if(!o)return;const c={x:o.x+o.w/2,y:o.y+o.h/2},a=Math.atan2(p.y-c.y,p.x-c.x)*180/Math.PI;o.rotation=(Math.round((a+90)/5)*5+360)%360;render();}}
  function onUp(){if(state.marquee){const m=state.marquee,x1=Math.min(m.x,m.cx),x2=Math.max(m.x,m.cx),y1=Math.min(m.y,m.cy),y2=Math.max(m.y,m.cy),hits=state.doc.objects.filter(o=>o.type!=='room'&&o.x<=x2&&o.x+o.w>=x1&&o.y<=y2&&o.y+o.h>=y1).map(o=>o.id);state.selectedIds=m.additive?[...new Set([...m.before,...hits])]:hits;state.selectedId=state.selectedIds.at(-1)||null;state.marquee=null;render();$('properties').classList.add('open');return;}if(state.drag){if(state.drag.moved){state.history.push(state.drag.before);state.future=[];state.drag.starts.forEach(s=>{const o=objectById(s.id);if(o)snapToWall(o);});render();autoSave();}state.drag=null;}if(state.resize){state.history.push(state.resize.before);state.future=[];state.resize=null;autoSave();}if(state.rotate){state.history.push(state.rotate.before);state.future=[];state.rotate=null;autoSave();}}
  function startResize(e,corner){e.stopPropagation();const o=selected();if(!o||o.wall)return;const p=point(e);state.resize={id:o.id,corner,startX:p.x,startY:p.y,ox:o.x,oy:o.y,ow:o.w,oh:o.h,size:o.size||20,before:snapshot()};$('drawing').setPointerCapture?.(e.pointerId);}
  function startRotate(e){e.stopPropagation();const o=selected();if(!o)return;state.rotate={id:o.id,before:snapshot()};$('drawing').setPointerCapture?.(e.pointerId);}
  function select(id){state.selectedId=id;state.selectedIds=id?[id]:[];renderSelection();updateProperties();if(id)$('properties').classList.add('open');}
  function deselect(){state.selectedId=null;state.selectedIds=[];state.marquee=null;$('properties').classList.remove('open');render();}
  function makeFromTool(tool,p){const type=tool.startsWith('symbol:')?'symbol':tool;const symbol=tool.split(':')[1];if(type==='symbol'){const d=symbolDims(symbol);return{id:uid(),type:'symbol',symbol,x:clamp(snap(p.x-d.w/2),0,W-d.w),y:clamp(snap(p.y-d.h/2),0,H-d.h),w:d.w,h:d.h,rotation:0,label:''};}if(type==='room'){const w=300,h=240;return{id:uid(),type:'room',name:'Room',x:clamp(snap(p.x-w/2),0,W-w),y:clamp(snap(p.y-h/2),0,H-h),w,h};}if(type==='divider')return{id:uid(),type:'divider',...clone(DEFAULTS.divider),y:snap(p.y)};if(type==='box')return{id:uid(),type:'box',...clone(DEFAULTS.box),label:'Box',x:clamp(snap(p.x-100),0,W-200),y:clamp(snap(p.y-40),0,H-80)};if(type==='text')return{id:uid(),type:'text',...clone(DEFAULTS.text),x:snap(p.x),y:snap(p.y),label:'New label'};return{id:uid(),type:'legend',...clone(DEFAULTS.legend)};}
  function objectLabel(o){return o.type==='symbol'?LABELS[o.symbol]:({room:'Room',divider:'Divider',box:'Box',text:'Text',legend:'Legend'}[o.type]||o.type);}
  function setTool(tool){state.tool=tool;qsa('[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));$('statusText').textContent=tool==='select'?'Select, move, rotate, or resize an object':'Tap the page to place '+(tool.startsWith('symbol:')?LABELS[tool.slice(7)]:objectLabel({type:tool}));if(tool==='select')renderSelection();else $('selectionLayer').innerHTML='';if(tool==='legend'){record();state.doc.objects.push(makeFromTool(tool,{x:W-100,y:100}));state.selectedId=state.doc.objects.at(-1).id;state.selectedIds=[state.selectedId];state.tool='select';setTool('select');render();}closeAddSheet();}
  function updateProperties(){const os=selectedObjects(),single=$('singlePropertyFields'),group=$('groupProperties');if(!os.length){$('propertiesForm').hidden=true;$('propertiesEmpty').hidden=false;return;}$('propertiesForm').hidden=false;$('propertiesEmpty').hidden=true;group.hidden=os.length<2;single.hidden=os.length>1;if(os.length>1){$('selectedTypeBadge').textContent='GROUP';$('selectedType').textContent='Multiple objects';$('groupCount').textContent=`${os.length} objects`;return;}const o=os[0];$('selectedTypeBadge').textContent=objectLabel(o).toUpperCase();$('selectedType').textContent=objectLabel(o);$('propLabel').value=o.label||o.name||o.text||'';$('propX').value=Math.round(o.x||0);$('propY').value=Math.round(o.y||0);$('propW').value=Math.round(o.w||40);$('propH').value=Math.round(o.h||40);$('propRotation').value=o.rotation||0;$('rotationValue').textContent=`${o.rotation||0}°`;}
  function updateSelected(key,value){const o=selected();if(!o)return;record();if(key==='label'){o.label=value;if(o.type==='room')o.name=value;if(o.type==='text')o.text=value;}else{o[key]=Number(value);o.w=Math.max(8,o.w);o.h=Math.max(8,o.h);o.x=clamp(o.x,0,W-o.w);o.y=clamp(o.y,0,H-o.h);}render();autoSave();}
  function rotate(delta){const o=selected();if(!o)return toast('Select an object first');record();o.rotation=((o.rotation||0)+delta+360)%360;render();autoSave();}
  function deleteSelected(){const ids=new Set(state.selectedIds.length?state.selectedIds:[state.selectedId].filter(Boolean));if(!ids.size)return toast('Select an object first');record();state.doc.objects=state.doc.objects.filter(o=>!ids.has(o.id));state.selectedId=null;state.selectedIds=[];render();autoSave();toast(`${ids.size} object${ids.size===1?'':'s'} deleted`);}
  function duplicate(){const os=selectedObjects();if(!os.length)return toast('Select an object first');record();const copies=os.map(o=>{const c=clone(o);c.id=uid();c.x=clamp((c.x||0)+SNAP,0,W-(c.w||40));c.y=clamp((c.y||0)+SNAP,0,H-(c.h||40));state.doc.objects.push(c);return c.id;});state.selectedIds=copies;state.selectedId=copies.at(-1);render();autoSave();}
  function order(front){const ids=new Set(state.selectedIds);if(!ids.size)return;record();const moving=state.doc.objects.filter(o=>ids.has(o.id)),rest=state.doc.objects.filter(o=>!ids.has(o.id));state.doc.objects=front?[...rest,...moving]:[...moving,...rest];render();autoSave();}

  function stripComment(line){let quoted=false;for(let i=0;i<line.length;i++){if(line[i]==='"')quoted=!quoted;if(line[i]==='#'&&!quoted)return [line.slice(0,i),line.slice(i+1)];}return[line,''];}
  function kv(rest){const out={};const re=/(\w+)=("[^"]*"|'[^']*'|[^\s]+)/g;let m;while((m=re.exec(rest)))out[m[1].toLowerCase()]=m[2].replace(/^['"]|['"]$/g,'');return out;}
  function quoted(text){const m=text.match(/"([^"]*)"|'([^']*)'/);return m?(m[1]??m[2]):'';}
  /* Re-declare with Unicode escapes so smart quotes work regardless of file encoding. */
  function cleanScript(input){let s=String(input||'').replace(/[\u201c\u201d]/g,'"').replace(/[\u2018\u2019]/g,"'").replace(/```[a-z]*|```/gi,'');const i=s.search(/\bELS\s+1\b/i);if(i>=0)s=s.slice(i);return s.replace(/\r/g,'').split('\n');}
  function suggestion(token){const words=['led','fan','socket15','socket5','room','divider','box','text','legend','page'];let best='',score=99;for(const w of words){let d=Math.abs(w.length-token.length);for(let i=0;i<Math.min(w.length,token.length);i++)if(w[i]!==token[i])d++;if(d<score){score=d;best=w;}}return score<=4?` Did you mean “${best}”?`:'';}
  function makeId(raw,used){let id=raw||`o${used.next++}`;if(used.ids.has(id))return null;used.ids.add(id);return id;}
  function parseAt(text,room){const m=text.match(/(?:^|\s)at\s+([^\s]+),([^\s]+)/i);return m?{x:parsePosition(m[1],'x',room),y:parsePosition(m[2],'y',room)}:null;}
  function parseELS(input){const lines=cleanScript(input),errors=[],warnings=[],objects=[],patches=[],used={ids:new Set(),next:1};if(lines.length>5000)return{mode:'replace',page:{...state.doc.page},objects:[],patches:[],errors:['Script exceeds the 5,000-line safety limit.'],warnings:[],counts:{}};let header=false,mode='replace',room=null,page={...state.doc.page};const add=(o,line)=>{if(o.wall)wallToFree(o,room);if(objects.length>=50000){errors.push(`Line ${line}: script exceeds the 50,000-object safety limit`);return;}if(![o.x,o.y,o.w,o.h].every(Number.isFinite)||o.w<8||o.h<8){errors.push(`Line ${line}: object coordinates and size must be valid, with width and height at least 8`);return;}if(!o.id)o.id=makeId(null,used);else if(used.ids.has(o.id))errors.push(`Line ${line}: duplicate id “${o.id}”`);else used.ids.add(o.id);objects.push(o);};for(let i=0;i<lines.length;i++){let raw=lines[i].trim();if(!raw)continue;const [withoutComment,comment]=stripComment(raw);raw=withoutComment.trim();if(comment.trim().startsWith('?'))warnings.push(`Line ${i+1}: uncertain item — please check`);if(!raw)continue;if(!header){const hm=raw.match(/^ELS\s+1(?:\s+(patch))?/i);if(!hm){errors.push(`Line ${i+1}: script must begin with ELS 1`);continue;}header=true;mode=hm[1]?'patch':'replace';continue;}if(/^page\b/i.test(raw)){const pm=raw.match(/^page\s+(\S+)\s+(portrait|landscape)(?:\s+border)?/i);if(!pm){errors.push(`Line ${i+1}: page syntax is page A4 portrait border`);continue;}page={...page,size:pm[1].toUpperCase(),orientation:pm[2].toLowerCase(),w:pm[2].toLowerCase()==='portrait'?800:1130,h:pm[2].toLowerCase()==='portrait'?1130:800};continue;}
      let canonical=raw.toLowerCase().replace(/^ceiling\s+fan\b/,'fan').replace(/^light\b|^lamp\b|^bulb\b|^point\b/,'led').replace(/^15a\b|^power\s+socket\b|^socket\s+15\b/,'socket15').replace(/^5a\b|^socket\s+5\b/,'socket5');let token=(canonical.match(/^\w+/)||[''])[0];
      if(mode==='patch' && /^(move|rotate|label|delete)\b/i.test(canonical)){const pm=raw.match(/^move\s+@(\S+)\s+to\s+([^\s]+),([^\s]+)/i);if(pm)patches.push({kind:'move',id:pm[1],x:pm[2],y:pm[3],line:i+1});else{const rm=raw.match(/^rotate\s+@(\S+)\s+to\s+(-?\d+)/i),lm=raw.match(/^label\s+@(\S+)\s+["']([^"']*)["']/i),dm=raw.match(/^delete\s+@(\S+)/i),dw=raw.match(/^delete\s+(led|fan|socket15|socket5)\s+where\s+y=([^\s]+)/i);if(rm)patches.push({kind:'rotate',id:rm[1],value:Number(rm[2]),line:i+1});else if(lm)patches.push({kind:'label',id:lm[1],value:lm[2],line:i+1});else if(dm)patches.push({kind:'delete',id:dm[1],line:i+1});else if(dw)patches.push({kind:'deleteWhere',symbol:dw[1].toLowerCase(),y:dw[2],line:i+1});else errors.push(`Line ${i+1}: invalid patch command`);}continue;}
      if(/^room\b/i.test(canonical)){const m=raw.match(/^room\s+(?:"([^"]+)"|'([^']+)'|(\S+))\s+at\s+([^\s]+)\s+size\s+(\S+)(.*)$/i);if(!m){errors.push(`Line ${i+1}: room syntax is room "Name" at X,Y size WxH`);continue;}const at=m[4].split(','),sz=m[5].toLowerCase().split('x'),opts=kv(m[6]);room={id:opts.id||`room${objects.filter(x=>x.type==='room').length+1}`,type:'room',name:m[1]||m[2]||m[3],x:num(at[0]),y:num(at[1]),w:num(sz[0]),h:num(sz[1]),strokeWidth:4};add(room,i+1);continue;}
      if(/^divider\b/i.test(canonical)){const m=canonical.match(/^divider\s+([hv])\s+at\s+([^\s]+)(.*)$/i);if(!m){errors.push(`Line ${i+1}: divider syntax is divider h|v at 55% dashed`);continue;}const opts=kv(m[3]),pos=parsePosition(m[2],m[1]==='h'?'y':'x',room),o={id:opts.id,type:'divider',orientation:m[1].toLowerCase(),x:room?.x||40,y:room?.y||80,w:room?.w||700,h:room?.h||1050,dashed:true};if(o.orientation==='h')o.y=pos;else{o.x=pos;o.y=room?.y||80;}add(o,i+1);continue;}
      if(['led','fan','socket15','socket5'].includes(token)){const rest=raw.slice(raw.toLowerCase().indexOf(token)+token.length),opts=kv(rest),wall=(opts.wall||'').toLowerCase(),d=symbolDims(token),base={type:'symbol',symbol:token,w:d.w,h:d.h,rotation:Number(opts.rot||0),label:opts.label||''};if(wall){if(!['left','right','top','bottom'].includes(wall)){errors.push(`Line ${i+1}: wall must be left, right, top, or bottom`);continue;}const rawAlong=wall==='top'||wall==='bottom'?opts.x:opts.y;if(rawAlong==null){errors.push(`Line ${i+1}: ${token} needs wall= plus x= or y=`);continue;}const vals=rawAlong.split(',');vals.forEach(a=>add({...base,id:opts.id&&vals.length===1?opts.id:undefined,wall,along:num(a),room:room?.id},i+1));continue;}const p=parseAt(rest,room),xs=opts.x?opts.x.split(','):p?[String(p.x)]:[],ys=opts.y?opts.y.split(','):p?[String(p.y)]:[];if(!xs.length||!ys.length){errors.push(`Line ${i+1}: ${token} needs at= coordinates or x= and y=`);continue;}xs.forEach(xv=>ys.forEach(yv=>add({...base,id:opts.id&&xs.length===1&&ys.length===1?opts.id:undefined,x:parsePosition(xv,'x',room)-d.w/2,y:parsePosition(yv,'y',room)-d.h/2,room:room?.id},i+1)));continue;}
      if(/^box\b/i.test(raw)){const m=raw.match(/^box\s+(?:"([^"]*)"|'([^']*)')\s+at\s+([^\s]+)\s+size\s+(\S+)(.*)$/i);if(!m){errors.push(`Line ${i+1}: box syntax is box "LED TV" at X,Y size WxH`);continue;}const at=m[3].split(','),sz=m[4].toLowerCase().split('x'),opts=kv(m[5]);add({id:opts.id,type:'box',label:(m[1]||m[2]||'').replace(/\\n/g,'\n'),x:parsePosition(at[0],'x',room),y:parsePosition(at[1],'y',room),w:num(sz[0]),h:num(sz[1]),labelPos:opts.label||'inside'},i+1);continue;}
      if(/^text\b/i.test(raw)){const m=raw.match(/^text\s+(?:"([^"]*)"|'([^']*)')\s+at\s+([^\s]+)\s+size\s+(\S+)(.*)$/i);if(!m){errors.push(`Line ${i+1}: text syntax is text "Label" at X,Y size 20`);continue;}const at=m[3].split(','),opts=kv(m[5]);add({id:opts.id,type:'text',label:(m[1]||m[2]||'').replace(/\\n/g,'\n'),x:parsePosition(at[0],'x',room),y:parsePosition(at[1],'y',room),w:220,h:num(m[4])+8,size:num(m[4]),align:opts.align||'start'},i+1);continue;}
      if(/^legend\b/i.test(raw)){const m=raw.match(/^legend\s+auto\s+at\s+(.+)$/i);if(!m){errors.push(`Line ${i+1}: legend syntax is legend auto at right`);continue;}const parts=m[1].trim().split(/\s+/),place=parts[0],opts=kv(m[1].slice(place.length));let x=20,y=100;if(place.toLowerCase()==='right')x=W-200;else if(place.toLowerCase()==='left')x=20;else{const at=place.split(',');x=num(at[0]);y=num(at[1]);}add({id:opts.id,type:'legend',auto:true,x,y,w:195,h:220},i+1);continue;}
      errors.push(`Line ${i+1}: unknown command “${token||raw.split(/\s+/)[0]}”.${suggestion(token||raw.split(/\s+/)[0])}`);
    }
    if(!header)errors.push('Missing ELS 1 header');const ids=new Set();objects.forEach(o=>{if(ids.has(o.id))errors.push(`Duplicate id “${o.id}”`);ids.add(o.id);});if(room)objects.forEach(o=>{if(o.type==='symbol'&&o.wall)return;const cx=o.type==='text'?o.x:(o.x||0)+(o.w||0)/2,cy=o.type==='text'?o.y:(o.y||0)+(o.h||0)/2;if(o.type!=='room'&&o.type!=='legend'&&(cx<room.x||cx>room.x+room.w||cy<room.y||cy>room.y+room.h))warnings.push(`${o.id}: item is outside room “${room.name}”`);});const counts={};objects.forEach(o=>{const k=o.type==='symbol'?o.symbol:o.type;counts[k]=(counts[k]||0)+1;});return{mode,page,objects,patches,errors,warnings,counts};}
  function applyPatches(parsed,base){const objects=clone(base.objects),find=id=>objects.find(o=>o.id===id),room=objects.find(o=>o.type==='room');for(const p of parsed.patches){if(p.kind==='delete'){const i=objects.findIndex(o=>o.id===p.id);if(i<0)parsed.errors.push(`Line ${p.line}: object @${p.id} was not found`);else objects.splice(i,1);}else if(p.kind==='deleteWhere'){for(let i=objects.length-1;i>=0;i--)if(objects[i].type==='symbol'&&objects[i].symbol===p.symbol&&Math.abs((objects[i].y-(room?.y||0))/(room?.h||1)*100-num(p.y))<1)objects.splice(i,1);}else{const o=find(p.id);if(!o){parsed.errors.push(`Line ${p.line}: object @${p.id} was not found`);continue;}if(p.kind==='rotate')o.rotation=p.value;if(p.kind==='label')o.label=p.value;if(p.kind==='move'){const x=parsePosition(p.x,'x',room),y=parsePosition(p.y,'y',room);if(o.type==='symbol'){o.x=x-o.w/2;o.y=y-o.h/2;}else{o.x=x;o.y=y;}}}}return objects;}
  function appendWithoutIdClashes(base,extra){const used=new Set(base.map(o=>o.id)),map=new Map(),added=clone(extra);for(const o of added)if(used.has(o.id)){const old=o.id;o.id=uid();map.set(old,o.id);}for(const o of added)if(o.room&&map.has(o.room))o.room=map.get(o.room);return[...base,...added];}
  function parsedDoc(parsed,mode){if(parsed.mode==='patch'){const patched=applyPatches(parsed,state.doc);return{...clone(state.doc),page:parsed.page,objects:appendWithoutIdClashes(patched,parsed.objects)};}const newObjects=mode==='add'?appendWithoutIdClashes(clone(state.doc.objects),parsed.objects):clone(parsed.objects);return{...clone(state.doc),page:parsed.page,objects:newObjects};}
  function summary(parsed){return Object.entries(parsed.counts).map(([k,v])=>`+${v} ${LABELS[k]||({room:'room',divider:'divider',box:'box',text:'text',legend:'legend'}[k]||k)}`).join(', ')||'No objects';}
  function previewScript(){const p=parseELS($('elsInput').value);state.lastImport=p;const report=$('scriptReport');$('previewLayer').innerHTML='';if(p.errors.length){report.innerHTML=`<div class="report-error"><strong>Nothing applied.</strong><br>${p.errors.join('<br>')}</div>`;$('applyScriptBtn').disabled=true;return;}const next=parsedDoc(p,$('scriptMode').value);if(p.errors.length){report.innerHTML=`<div class="report-error"><strong>Nothing applied.</strong><br>${p.errors.join('<br>')}</div>`;$('applyScriptBtn').disabled=true;return;}p.previewDoc=next;state.preview={objects:next.objects};p.warnings.length?report.innerHTML=`<div class="report-ok"><strong>${summary(p)}</strong> ready to preview</div><div class="report-warn">${p.warnings.join('<br>')}</div>`:report.innerHTML=`<div class="report-ok"><strong>${summary(p)}</strong> ready to preview</div>`;state.preview=next;next.objects.forEach(o=>renderObject(o,$('previewLayer'),true));$('applyScriptBtn').disabled=false;}
  function applyScript(){const p=state.lastImport;if(!p||p.errors.length||!p.previewDoc)return;record();state.doc=clone(p.previewDoc);state.selectedId=null;state.selectedIds=[];state.preview=null;$('previewLayer').innerHTML='';render();autoSave();$('scriptReport').innerHTML=`<div class="report-ok">Applied in one undo step. Use Tidy layout if coordinates need grouping.</div>`;toast('Script applied');}
  function tidy(){const r=state.doc.objects.find(o=>o.type==='room');if(!r)return toast('Add a room before tidying');record();const syms=state.doc.objects.filter(o=>o.type==='symbol'&&!o.wall);const tol=r.w*.015;for(const a of syms){for(const b of syms){if(a===b)continue;if(Math.abs(a.x-b.x)<tol)a.x=b.x;if(Math.abs(a.y-b.y)<tol)a.y=b.y;}}state.doc.objects.filter(o=>o.type==='symbol'&&o.wall).forEach(o=>o.along=clamp(o.along??50,0,100));render();autoSave();toast('Layout tidied');}
  function exportELS(){const lines=['ELS 1',`page ${state.doc.page.size||'A4'} ${state.doc.page.orientation||'portrait'} border`];for(const o of state.doc.objects){if(o.type==='room')lines.push(`room "${o.name||'Room'}" at ${round(o.x)},${round(o.y)} size ${round(o.w)}x${round(o.h)} id=${o.id}`);else if(o.type==='divider')lines.push(`divider ${o.orientation||'h'} at ${round(o.orientation==='h'?o.y:o.x)} dashed id=${o.id}`);else if(o.type==='symbol'){if(o.wall)lines.push(`${o.symbol} wall=${o.wall} ${o.wall==='top'||o.wall==='bottom'?'x':'y'}=${round(o.along)} id=${o.id}`);else lines.push(`${o.symbol} at ${round(o.x+o.w/2)},${round(o.y+o.h/2)} rot=${round(o.rotation||0)}${o.label?` label="${o.label}"`:''} id=${o.id}`);}else if(o.type==='box')lines.push(`box "${(o.label||'').replace(/\n/g,'\\n')}" at ${round(o.x)},${round(o.y)} size ${round(o.w)}x${round(o.h)} label=${o.labelPos||'inside'} id=${o.id}`);else if(o.type==='text')lines.push(`text "${(o.label||o.text||'').replace(/\n/g,'\\n')}" at ${round(o.x)},${round(o.y)} size ${round(o.size||20)} align=${o.align||'start'} id=${o.id}`);else if(o.type==='legend')lines.push(`legend auto at ${round(o.x)},${round(o.y)} id=${o.id}`);}return lines.join('\n');}
  function round(n){return Math.round(Number(n)||0);}

  const PROMPTS={A:`You convert electrical layout sketches into ELS 1. Reply with ONE code block containing only the script.\n\nALLOWED OBJECTS ONLY: led, fan, socket15, socket5, room, divider, box (a rectangle holding any text; use \\n for new lines), text, legend. Symbols: led = small circle; fan = circle with figure-8; socket15 = half-circle with an inner half-circle and 3 rays; socket5 = single half-circle with 3 rays. These are the project's house-v1 reference symbols, not claimed IS/IEC symbols.\n\nUse page A4 portrait border, a room, percentage positions for repeated symbols, wall=left|right|top|bottom for sockets, and a final legend auto at right. If unclear, add a comment beginning # ?.\n\nExample:\nELS 1\npage A4 portrait border\nroom "Hall" at 40,80 size 520x1050\nled x=15%,34%,65%,80% y=9%,19%,29%\nfan at 28%,40%\nsocket15 wall=right y=9%,18%\nbox "AIR CURTAIN" at 31%,67% size 250x50 label=inside\nlegend auto at right\n\nNow convert the attached sketch.`,B:`Below is my current electrical drawing as ELS 1. Return ONE code block only. Use ELS 1 patch for a small change; use a complete ELS 1 script for a large change. Allowed objects: led, fan, socket15, socket5, room, divider, box, text, legend.\n\nCURRENT SCRIPT:\n${exportELS()}\n\nCHANGE REQUESTED:\n`,C:`Fix this ELS 1 script. Return ONE code block only, with no explanation.\n\nERRORS:\n${$('scriptReport').innerText||'(paste the errors here)'}\n\nSCRIPT:\n${$('elsInput').value}`};
  function setPrompt(k){qsa('[data-prompt]').forEach(b=>b.classList.toggle('active',b.dataset.prompt===k));$('promptOutput').value=PROMPTS[k];}

  function save(){localStorage.setItem(STORAGE,JSON.stringify({...state.doc,_nextId:state.nextId,title:$('drawingName').value}));state.dirty=false;toast('Saved on this device');}
  function autoSave(){clearTimeout(autoSave.t);autoSave.t=setTimeout(()=>save(),250);}
  function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE)||'null');if(d&&Array.isArray(d.objects)){d.objects.forEach(o=>o.wall&&wallToFree(o,d.objects.find(r=>r.type==='room')));state.doc={version:d.version||1,symbolSet:d.symbolSet||'house-v1',page:{...state.doc.page,...d.page},objects:d.objects};state.nextId=d._nextId||state.doc.objects.length+1;$('drawingName').value=d.title||'Electrical layout 1';return true;}}catch(e){}return false;}
  function download(name,blob){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
  function svgString(){const copy=$('drawing').cloneNode(true);copy.querySelector('#selectionLayer')?.remove();copy.querySelector('#previewLayer')?.remove();copy.querySelector('#grid')?.remove();copy.setAttribute('xmlns',NS);copy.setAttribute('width',state.doc.page.w);copy.setAttribute('height',state.doc.page.h);const style=document.createElementNS(NS,'style');style.textContent='.room-stroke{fill:none;stroke:#111;stroke-width:4}.divider-stroke{fill:none;stroke:#111;stroke-width:1.7;stroke-dasharray:8 7}.symbol-stroke{fill:none;stroke:#111;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.object-label{fill:#111;font-family:Arial,sans-serif;font-size:13px;font-weight:600;text-anchor:middle}';copy.querySelector('defs').appendChild(style);return new XMLSerializer().serializeToString(copy);}
  function exportSvg(){download('electrical-layout.svg',new Blob([svgString()],{type:'image/svg+xml'}));closeModal('exportModal');toast('SVG downloaded');}
  function exportPng(){const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=1600;c.height=Math.round(1600*H/W);const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(img,0,0,c.width,c.height);c.toBlob(b=>download('electrical-layout.png',b),'image/png');};img.src='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svgString());closeModal('exportModal');toast('PNG downloaded');}
  function exportJson(){download('electrical-layout.json',new Blob([JSON.stringify({...state.doc,_nextId:state.nextId,title:$('drawingName').value},null,2)],{type:'application/json'}));closeModal('exportModal');toast('JSON backup downloaded');}
  async function share(){const text=exportELS();if(navigator.share){try{await navigator.share({title:$('drawingName').value,text});}catch(e){}}else{await copy(text);toast('Script copied — ready to share');}}
  async function copy(text){try{await navigator.clipboard.writeText(text);return true;}catch(e){const t=document.createElement('textarea');t.value=text;document.body.appendChild(t);t.select();document.execCommand('copy');t.remove();return true;}}
  function openModal(id){$(id).removeAttribute('hidden')}function closeModal(id){$(id).setAttribute('hidden','');if(id==='scriptModal'){$('previewLayer').innerHTML='';state.preview=null;}}function closeAddSheet(){$('addSheet').setAttribute('hidden','');}
  function toast(message){const t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200);}
  function setZoom(z){state.zoom=clamp(z,.6,1.5);$('drawing').style.width=`${Math.round(W*state.zoom)}px`;$('zoomValue').textContent=`${Math.round(state.zoom*100)}%`;}

  qsa('[data-tool^="symbol:"]').forEach(b=>{const k=b.dataset.tool.slice(7),d=symbolDims(k),v=svgEl('svg',{viewBox:`0 0 ${d.w} ${d.h}`,width:34,height:26,class:'sym-icon'});drawReferenceSymbol(v,k,d.w,d.h);v.querySelectorAll('*').forEach(e=>e.setAttribute('vector-effect','non-scaling-stroke'));const t=b.querySelector('.tile-symbol');if(t){t.textContent='';t.appendChild(v);}else b.firstChild.replaceWith(v);});
  qsa('[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
  $('drawing').addEventListener('pointerdown',onCanvasDown);$('drawing').addEventListener('pointermove',onMove);$('drawing').addEventListener('pointerup',onUp);$('drawing').addEventListener('pointercancel',onUp);
  $('undoBtn').onclick=undo;$('redoBtn').onclick=redo;$('saveBtn').onclick=save;$('exportBtn').onclick=()=>openModal('exportModal');$('zoomInBtn').onclick=()=>setZoom(state.zoom+.1);$('zoomOutBtn').onclick=()=>setZoom(state.zoom-.1);$('gridButton').onclick=()=>{$('gridToggleBtn').click()};$('gridToggleBtn').onclick=()=>{state.grid=!state.grid;$('gridToggleBtn').textContent=`Grid: ${state.grid?'on':'off'}`;render()};$('snapBtn').onclick=()=>{state.snap=!state.snap;$('snapBtn').textContent=`Snap: ${state.snap?'on':'off'}`};$('tidyBtn').onclick=tidy;$('newDrawingBtn').onclick=()=>openModal('newModal');$('confirmNewBtn').onclick=()=>{record();state.doc.objects=[];state.selectedId=null;state.selectedIds=[];closeModal('newModal');render();autoSave();toast('Blank drawing created');};
  [['propLabel','label'],['propX','x'],['propY','y'],['propW','w'],['propH','h']].forEach(([id,key])=>$(id).addEventListener('change',e=>updateSelected(key,e.target.value)));$('propRotation').addEventListener('pointerdown',()=>state.rotBefore=snapshot());$('propRotation').addEventListener('input',e=>{const o=selected();if(o){o.rotation=Number(e.target.value);render();}});$('propRotation').addEventListener('change',()=>{if(state.rotBefore){state.history.push(state.rotBefore);state.future=[];state.rotBefore=null;autoSave();}});$('rotateLeftBtn').onclick=()=>rotate(-90);$('rotateRightBtn').onclick=()=>rotate(90);$('rotate180Btn').onclick=()=>rotate(180);$('bringFrontBtn').onclick=()=>order(true);$('sendBackBtn').onclick=()=>order(false);$('propDuplicateBtn').onclick=duplicate;$('groupDuplicateBtn').onclick=duplicate;$('groupDeleteBtn').onclick=deleteSelected;$('propertyDeleteBtn').onclick=deleteSelected;$('closeProperties').onclick=deselect;
  $('scriptBtn').onclick=()=>{openModal('scriptModal');$('elsInput').focus()};$('scriptMobileBtn').onclick=()=>openModal('scriptModal');$('aiHelperBtn').onclick=()=>{setPrompt('A');openModal('aiModal')};$('previewScriptBtn').onclick=previewScript;$('applyScriptBtn').onclick=applyScript;$('copyScriptBtn').onclick=async()=>{await copy(exportELS());toast('ELS script copied')};qsa('[data-script-tab]').forEach(b=>b.onclick=()=>{qsa('[data-script-tab]').forEach(x=>x.classList.toggle('active',x===b));$('scriptImportPanel').hidden=b.dataset.scriptTab!=='import';$('scriptExportPanel').hidden=b.dataset.scriptTab!=='export';if(b.dataset.scriptTab==='export')$('elsOutput').value=exportELS();});qsa('[data-prompt]').forEach(b=>b.onclick=()=>setPrompt(b.dataset.prompt));$('copyPromptBtn').onclick=async()=>{await copy($('promptOutput').value);toast('Prompt copied')};
  $('exportSvg').onclick=exportSvg;$('exportPng').onclick=exportPng;$('exportJson').onclick=exportJson;$('shareBtn').onclick=share;$('printBtn').onclick=()=>{closeModal('exportModal');window.print()};$('importJsonBtn').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const d=JSON.parse(reader.result);if(!Array.isArray(d.objects))throw Error();d.objects.forEach(o=>o.wall&&wallToFree(o,d.objects.find(r=>r.type==='room')));record();state.doc={version:d.version||1,symbolSet:d.symbolSet||'house-v1',page:{...state.doc.page,...d.page},objects:d.objects};state.nextId=d._nextId||state.doc.objects.length+1;$('drawingName').value=d.title||'Imported drawing';closeModal('exportModal');render();autoSave();toast('JSON backup imported');}catch(err){toast('Could not read that JSON backup')}};reader.readAsText(file);};
  $('addMobileBtn').onclick=()=>openModal('addSheet');$('scriptMobileBtn').onclick=()=>openModal('scriptModal');$('moreMobileBtn').onclick=()=>{$('sidebar').classList.toggle('mobile-open')};qsa('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));qsa('.modal-backdrop').forEach(m=>m.addEventListener('pointerdown',e=>{if(e.target===m)closeModal(m.id)}));
  $('drawingName').addEventListener('change',autoSave);document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();undo()}else if((e.ctrlKey||e.metaKey)&&e.key==='y'){e.preventDefault();redo()}else if((e.key==='Delete'||e.key==='Backspace')&&!['INPUT','TEXTAREA'].includes(document.activeElement.tagName))deleteSelected();else if(e.key==='Escape'){deselect();setTool('select')}});
  if(!load())seed();function seed(){const s=`ELS 1\npage A4 portrait border\nroom "Hall" at 40,80 size 520x1050\ndivider h at 55% dashed\ndivider h at 67% dashed\ndivider h at 85% dashed\nled x=15%,34%,65%,80% y=9%,19%,29%,46%\nled x=15%,42%,64%,91% y=77%\nled x=15%,34%,64%,83% y=93%\nfan at 28%,40%\nfan at 74%,40%\nfan at 29%,77%\nfan at 78%,77%\nsocket15 wall=right y=5%,13%,21%,29%,36%,44%,52%\nsocket15 wall=left y=19%,29%,77%\nsocket5 wall=top x=48%\nbox "LED TV" at 17%,57% size 180x22 label=below\nbox "LED TV" at 52%,57% size 180x22 label=below\nbox "AIR CURTAIN" at 31%,67% size 250x50 label=inside\nlegend auto at right`;const p=parseELS(s);state.doc=parsedDoc(p,'replace');render();}
  render();setTool('select');setZoom(1);if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
})();
